default: &default
  adapter: postgresql
  encoding: unicode
  database: aaa
  host: localhost
  username: postgres
  password: 123
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aaa

test:
  <<: *default
  database: aaa

production:
  <<: *default
  database: aaa